name: .NET

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v1
    #   with:
    #     dotnet-version: 5.0.x

    - name: Checkout target branch
      uses: actions/checkout@v2

    - name: List Files
      run: |
        ls -al

    # - name: Execute code analysis
    #   run: ./CodeAnalyzer/start.sh
