name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Checkout target branch
      uses: actions/checkout@v2
      with: 
        ref: ${{ github.event.pull_request.head.sha }}
    
    - name: Execute code analysis
      run: ./CodeAnalyzer/start.sh
